### ISSUE TITLE
CIS Scoring

### ISSUE THREAD

**Issue by JArmandoG** [toniblyx/prowler#1079]
# What:
There are some controls checked by Prowler, which are not scored by CIS (For example, control/check 1.19 about Instance roles), and the Prowler output (CSV; JSON; etc.) does not clarify that.

# The Problem:
This control (Like many others) is not scored, and if the resource fails the check, it affects the report and the "prowler score". In cases where the resource doesn't need to comply with it (In this example, I have an EC2 which doesn't need an IAM Role since it doesn't do any AWS API call at all), this scoring or FAIL checks is misleading

# Why it's a problem:
Prowler does not deliver in the output whether the given check is scored or not, so I need to manually check in the CIS Benchmarks whether I'd need to do this or not, and if it's important or not. It takes some time to figure out why X resource failed, if it applies to the specific case, and go check if it's scored.

# The specific request:
So the request is specific to the implementation of the "Scored or not" checks for Prowler, that way it's a little bit easier to go through a lot of checks. This way we could maybe "filter" the CSV output by Scoring.

I know it's difficult since there may be 2 cases where the same check is important in one and not the other, but at least having a little bit of "tagging" would be helpful

**Comment by toniblyx** [comment]
Hi @JArmandoG I think there is a misunderstanding about what CIS Scored is and what Prowler Scoring is as well. 

First of all, they have nothing to do each other. CIS Scored checks are just CIS related and I have nothing to do with them, Prowler actually doesn´t do anything different if a check is scored or not, other than have that variable. What does mean a scored control in CIS? Go to page 6 in this pdf https://d0.awsstatic.com/whitepapers/compliance/AWS_CIS_Foundations_Benchmark.pdf but basically this:
![Screenshot 2022-03-24 at 10 42 12](https://user-images.githubusercontent.com/3985464/159888187-d18feb11-0111-4bf6-8634-a60ae22f95be.png)
So as I mentioned before, that scoring information doesn´t impact to Prowler actual scoring system at all. Prowler does not use CIS Scoring despite it is included on CIS related checks.

Prowler scoring feature is pretty straight forward and it works for all Prowler checks (CIS or extras or even if you use a group of checks or specific list of checks). Basically any PASS and FAIL is added to a counter, see:
https://github.com/prowler-cloud/prowler/blob/565200529f3280cdc3e328eac32c80a47b351b81/include/outputs#L103
https://github.com/prowler-cloud/prowler/blob/565200529f3280cdc3e328eac32c80a47b351b81/include/outputs#L197
https://github.com/prowler-cloud/prowler/blob/565200529f3280cdc3e328eac32c80a47b351b81/include/outputs#L248

And calculations are simple and you can see them here: https://github.com/prowler-cloud/prowler/blob/master/include/scoring

To be honest, I would take `severity` into consideration instead of `scoring`. 

In terms of tagging, we plan to add "categories" to checks in Prowler for v3 (new architecture of checks) later this year. I say categories instead of tags to not confuse them with the AWS resource tags but basically the same but for checks.

I hope this clarifies a bit what you are willing to have.

**Comment by JArmandoG** [comment]
Thank you for the extensive reply. This all makes sense, what I meant with "tags" was "scored" or "Not scored", just to give a little bit of extra info field from prowler. This way, I think we could filter out the resuts both by severity AND whether the check is CIS scored or not (When the check is grouped under cis levels).
