### ISSUE TITLE
[Bug]: check77 with PrincipalOrgPaths as Condition in ECR Repo Policy

### ISSUE THREAD

**Issue by gvasquez95** [toniblyx/prowler#1151]
**What happened?**  
check77 is reporting as public available repos that have `*` in the `Principal` but do have a condition that restricts access only from within the organization using the `PrincipalOrgPaths` clause

**How to reproduce it**  
Sample policy:
```
{
  "Version" : "2012-10-17",
  "Statement" : [ {
    "Sid" : "AllowPull",
    "Effect" : "Allow",
    "Principal" : "*",
    "Action" : [ "ecr:BatchCheckLayerAvailability", "ecr:BatchGetImage", "ecr:DescribeImages", "ecr:DescribeRepositories", "ecr:GetDownloadUrlForLayer", "ecr:ListImages" ],
    "Condition" : {
      "ForAnyValue:StringLike" : {
        "aws:PrincipalOrgPaths" : "o-dummy/*/ou-dummy/*"
      }
    }
  } ]
}
```

**Expected behavior**  
This is a border case, and it's being triggered in a false positive scenario.

**From where are you running Prowler?**  
Please, complete the following information:
Resource: [e.g. EC2 instance, Fargate task, Docker container manually, EKS, Cloud9, CodeBuild, workstation, etc.) : workstation
OS: [e.g. Amazon Linux 2, Mac, Alpine, Windows, etc. ] OSX
AWS-CLI Version [aws --version]:aws-cli/2.7.0 Python/3.9.11 Darwin/21.3.0 exe/x86_64 prompt/off
Prowler Version [./prowler -V]: Prowler 2.9.0-13April2022
Shell and version: /bin/bash GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin21)

**Comment by jfagoagas** [comment]
Thank you for your issue @gvasquez95, we are going to investigate this.

**Comment by n4ch04** [comment]
Hi @gvasquez95  after reviewing this we think that test (checking if the condition filters by organisations) is outside of the scope of the check.
Since we can't check if the value of the organisation is valid or not, we prefer to keep it this way (a general check) letting you to include that resource in the allowlist if you not want to have it as a fail record.
Also you can create a custom check to check explicitly this condition

Please feel free to reopen if something else appears and thank you for your contribution.
