### ISSUE TITLE
The security token included in the request is expired

### ISSUE THREAD

**Issue by mkannan22** [toniblyx/prowler#1165]
Is there a way to refresh the token while prowler is running so no checks are missed or a way to pause prowler before re-generating new token? I can refresh token at any point, but if prowler runs over the max session I receive the above error.

**Comment by toniblyx** [comment]
If you use the assume role functionality it will get refreshed before expiration. See documentation for -A and -R.

**Comment by mkannan22** [comment]
I am currently using the following command ./prowler -A 5555555555-R testrole -I test. I have tried to use the -T switch as well setting it to 43200, but the MaxSessionDuration set on this role is 3600. The environment is large, prowler continues to run, but returns the error above.

**Comment by toniblyx** [comment]
@mkannan22  could you please fill the issue form? We need more information in order to be able to help you. Thank you!

**Comment by mkannan22** [comment]
Examples of errors are: The security token included in the request is expired. An error occurred (RequestExpired) when calling the DescribeSecurityGroups operation: Request has expired. It does appear to continue to work after, I wasn't sure if some of the checks were going to be missed during those errors. Meaning while the refresh of token is occurring in background and this error displays, will those checks still get processed or skipped over?

**Comment by jfagoagas** [comment]
Hi @mkannan22, we can't reproduce your issue with the information you provide. We have been looking into it and we can't find any issue in the assume role logic.

As you can see here https://github.com/prowler-cloud/prowler/blob/2.10.0/prowler#L409-L424 when you use Prowler with a specific IAM role, before executing any Check we check if the remaining session time for that specific role is less than 10 minutes. In that case, we force the assume role logic again to renew the IAM session with that role.

So, in your case, even if your IAM Role has a `MaxSessionDuration` of 1 hour (3600 seconds), when your IAM session is about to expire (less than 10 minutes to this time) Prowler forces the session renewal to avoid stopping the execution due to the expiration of the security token.

Are you using the latest Prowler release? Please, check it here https://github.com/prowler-cloud/prowler/releases/tag/2.10.0

It would be much easier for us if you fulfil all the issue template attaching the `debug.txt` file.

If you can't provide us more information we will have to close this issue. 

Thanks!

**Comment by mkannan22** [comment]
This aligns with what I was seeing. I was confused that the message of The security token included in the request is expired was printed to the screen that checks were being skipped, but that seems to not be the case. The error message appears until token is refreshed in background and then checks begin again once token is refreshed (i.e. the error message no longer prints to the screen). I have also tested by increasing the MaxSessionDuration and everything works great. Thank you!

**Comment by jfagoagas** [comment]
Hi @mkannan22, I'm going to reopen this issue because I've been able to reproduce it. 

You're totally right, now I can see the `An error occurred (ExpiredToken) when calling the operation: The security token included in the request is expired`.

We are going to investigate it.

Thank you!

**Comment by jfagoagas** [comment]
We've identified the problem.

We transform the `AWS_SESSION_EXPIRATION` to `epoch` using the following `jq` code:
https://github.com/prowler-cloud/prowler/blob/432416d09ee40913732c0fc2ec8a21d7b85342ce/include/assume_role#L79

As you can see in the above `jq` issue, the dates are handled in the local timezone and not in `UTC`
https://github.com/stedolan/jq/issues/2001#issuecomment-1145864809


So, the issue here occurs when someone is using Prowler with a timezone different than `UTC`. In my case, using `CEST` the following occurs:
```
➜  prowler git:(master) ✗ date                                                            
Fri  3 Jun 2022 13:26:59 CEST
➜  prowler git:(master) ✗ echo '"2022-06-03T11:06:11+00:00"' |  jq '. | sub("\\+00:00";"Z") | strptime("%Y-%m-%dT%H:%M:%SZ")|mktime | todate' 
"2022-06-03T12:06:11Z"
```

![Screenshot 2022-06-03 at 13 27 24](https://user-images.githubusercontent.com/16007882/171845139-86896c38-c348-4e90-b75b-1b895e355757.png)
 
As you can see there is 1 hour delta between the right one and the bad one, just the difference of the summer time.

**Comment by jfagoagas** [comment]
Hi @mkannan22, please run Prowler from the following branch `PRWLR-526-the-security-token-included-in-the-request-is-expired-1165` and let us know if everything is okay using an IAM Role with a Max Session Duration of 1 hour (3600 seconds)

We've created this PR to address this issue: https://github.com/prowler-cloud/prowler/pull/1181

**Comment by mkannan22** [comment]
This seemed to fix the issue. Thanks for making the adjustment!
