### ISSUE TITLE
[Bug]:False positive Showing x-amz-credential as potential secret

### ISSUE THREAD

**Issue by RoxyR44** [toniblyx/prowler#1169]
Showing x-amz-credential as a potential secret:

1. Run prowler
2**. Finding 7.88:** EC2 Instance metadata and user data exposes a potential secret - FAIL! eu-west-1: Potential secret found in [instance] User Data
3.Prowler runs fine there is no issue, it's the finding that I am raising. 
 see stack overflow  https://stackoverflow.com/questions/34294685/is-showing-x-amz-credential-or-any-amazon-stuff-publicly-okay-in-form

**Comment by jfagoagas** [comment]
Hi @RoxyR44, could you fulfil the Bug issue template including the debug log appending `bash -x ./prowler ....`? We need more information to reproduce your issue.

If I understand you, the issue here is that `check7.88` is raising a PASS instead of a FAIL, due to the exposure of `x-amz-credential`?

**Comment by jfagoagas** [comment]
Hi @RoxyR44, we're closing this issue because we are not being able to reproduce it. Please, re-open this issue if you can provide us more information.

Please check this part https://github.com/prowler-cloud/prowler#set-the-entropy-limit-for-detect-secrets of the documentation to modify the `detect-secrets` entropy in order to detect or not some secrets if they are not. Another approach is to include this resource in the allowlist https://github.com/prowler-cloud/prowler#allowlist-or-remove-a-fail-from-resources.

For the next time if you fulfil the bug issue template it will be easier for us to triage and fix the issues you encounter.

Thank you!
