### ISSUE TITLE
[Bug]: prowler/prowler: line 525: ((: 600 > : syntax error: operand expected (error token is "> ")

### ISSUE THREAD

**Issue by zfLQ2qx2** [toniblyx/prowler#1186]
I'm getting the following error on Alpine Linux v3.16 - prowler/prowler: line 525: ((: 600 > : syntax error: operand expected (error token is "> ")

I'm not sure when this started, I just happened to be looking at the logs from my prowler run for an unrelated reason.

**Comment by toniblyx** [comment]
Thanks @zfLQ2qx2 can you give us more details? like the ones in the template, version, etc?

**Comment by jfagoagas** [comment]
Hi @zfLQ2qx2, could you please input the bug issue template?

We need the debug output executing `bash -x ./prowler 1>debug.txt 2>&1` to trace this error.

Doing an initial investigation the problem seems to be in the `$SESSION_TIME_REMAINING` variable, so if this value is empty the following error appears:
```
bash-5.1$ (( 500 > )) && echo si
bash: ((: 500 > : syntax error: operand expected (error token is "> ")
```

Please, test it again with Prowler at `master` branch because we've recently fix some issues in the `assume_role` logic.

Thanks!

**Comment by zfLQ2qx2** [comment]
I suspect this commit is the issue -- 1b63256b9cb0c6f6e47022fc219024b27943e33c

The date command appears to be the most non-portable thing ever, I've done several Prowler patches in the past for this, every platform seems to have its own date variant that takes wildly different options and input formats.

Since there is already some python in prowler, would be great if someone wrote a "universal" replacement for date. I tried once but my python skills aren't good enough.

I did a patch that used jq at one point instead since it seems to have the same output on every platform and jq is already used widely in the prowler checks.

I'll have time to debug in the next couple days if nobody beats me to it.

**Comment by jfagoagas** [comment]
Hi @zfLQ2qx2 you're right, `date` command is a nightmare. The problem with that commit is that we've identified some abnormal behaviour using `jq` to parse some timestamps. The problem was describe here https://github.com/prowler-cloud/prowler/pull/1181 

Also you can take a look at the `jq` issue here https://github.com/stedolan/jq/issues/2001#issuecomment-1145864809

The problem here is that the available `date` in AlpineLinux comes from `busybox`. Let me take a look into it, but it's time to create a Python library to handle dates and timestamps.

I'll keep you posted.

**Comment by zfLQ2qx2** [comment]
@jfagoagas Ah man! Good catch on stedolan's part. Yeah, Alpine does busybox which is great for containers (why I use it) but problem I've run into in the past is that even among different platforms that use busybox the compile time options and version of busybox result in binaries with very different capabilities. I think python would be the way to go since it seems to be a reoccurring and persistent problem.

I tested the previous commit 7930b449b3a341a0a45256ca99d21cced320074f and the error messages went away.

**Comment by jfagoagas** [comment]
@zfLQ2qx2 Yes, that's the problem with the same command across multiple linux distributions.

One temporary solution is to use our official container image which is built on top of Amazon Linux to avoid this problem. 

We're thinking how to support `date` from busybox at this moment but it's tough due to the different compilations and options in each distribution.

**Comment by zfLQ2qx2** [comment]
@jfagoagas one of my coworkers says it should be possible to write in python with only the base libraries, and it’s already used for the secret scanning so not a new requirement. I could whip one out in Perl or C in a minute but those come with a lot of overhead. One of the things I like best about Prowler is the most junior admin can look at the bash script and see how the checks work.

**Comment by zfLQ2qx2** [comment]
@jfagoagas idea! The jq solution did work except for the timezone, so maybe export TZ=UTC when calling it? You might want to do early on if you want all sub commands to run in UTC. Or you could just do it for the one place jq is called. I’m thinking the reason I didn’t see the timezone issue myself is I’m running my containers in UTC time.

**Comment by jfagoagas** [comment]
> @jfagoagas one of my coworkers says it should be possible to write in python with only the base libraries, and it’s already used for the secret scanning so not a new requirement. I could whip one out in Perl or C in a minute but those come with a lot of overhead. One of the things I like best about Prowler is the most junior admin can look at the bash script and see how the checks work.

@zfLQ2qx2  Yes! It is in our roadmap!

> @jfagoagas idea! The jq solution did work except for the timezone, so maybe export TZ=UTC when calling it? You might want to do early on if you want all sub commands to run in UTC. Or you could just do it for the one place jq is called. I’m thinking the reason I didn’t see the timezone issue myself is I’m running my containers in UTC time.

Good point! We'll test it. And yes if you are running Prowler in UTC you are not experiencing the issue, it only appears in summertime timezones.

**Comment by jfagoagas** [comment]
Please @zfLQ2qx2, check this PR https://github.com/prowler-cloud/prowler/pull/1195 and test it using this branch `PRWLR-556-bug-prowler-prowler-line-525-600-syntax-error-operand-expected-error-token-is`

I think this approach could work in every system.

**Comment by zfLQ2qx2** [comment]
Approach looks good, setting up a test run..

**Comment by zfLQ2qx2** [comment]
@jfagoagas Looks like a winner! 🥇

**Comment by jfagoagas** [comment]
@zfLQ2qx2 🎉 🎉 We still need to test it in different environments but yes, looks like the final boss has been defeated 😀

**Comment by zfLQ2qx2** [comment]
@jfagoagas Really awesome, switching back to master branch soon as I see the merge :)

**Comment by jfagoagas** [comment]
> @jfagoagas Really awesome, switching back to master branch soon as I see the merge :)

Thank you! Merged!!!
