### ISSUE TITLE
Access Denied trying to describe regions! Review permissions[Bug]: 

### ISSUE THREAD

**Issue by CenturionGamer** [toniblyx/prowler#1190]
Currently receiving an error, "Access Denied trying to describe regions! Review permissions," when running the latest version of prowler. I have not encountered this before, and checked the requirements and installation notes.

What permissions would be preventing the describe regions from executing?

Roger

**Comment by jfagoagas** [comment]
Hi @CenturionGamer, review this piece of code https://github.com/prowler-cloud/prowler/blob/bc56c4242ecbf6fdb40ca97114d1a1ab12c48754/prowler#L461-L470 because your error comes from this AWS API call. Check your AWS credentials and inspect if you can execute the following command:
`aws ec2 describe-regions --query 'Regions[].RegionName' --output text`

Also, fulfil the issue template and execute Prowler using `bash -x`, this help us a lot to triage your issue.

Thanks!

**Comment by CenturionGamer** [comment]
@jfagoagas - Thanks for the assistance! It's working now.
