### ISSUE TITLE
[extra7116] Is there a way to identify the table in the check result? 

### ISSUE THREAD

**Issue by NMuee** [toniblyx/prowler#1304]
Hi Team, 

Regarding to extra7116, is there a way list down the table names in the check results? 
Are we able to whitelist the tables too? 

Thank you

**Comment by jfagoagas** [comment]
Hi @NMuee, the purpose of `extra7116` is to review if the encryption at rest is enabled in AWS Glue, for that reason if there are not tables this check does not apply, because this configuration is at the service level and not at the table level.

So, I think we cannot whitelist a single table for this check because this configuration is at service level and applies for all objects.

For more information, please, take a look here https://docs.aws.amazon.com/glue/latest/dg/encrypt-glue-data-catalog.html

**Comment by NMuee** [comment]
Understand, Thank you for the explanation :)
