### ISSUE TITLE
[Bug]: Credentials expired during long running checks

### ISSUE THREAD

**Issue by zfLQ2qx2** [toniblyx/prowler#1499]
I've noticed that sometimes credentials expire during long running checks - for us notably S3 buckets because we have a lot of them, so if we are near the expiration and then need to run a check against several hundred buckets, the token can expire before renewing again,

The AWS SDKs solves this by checking the expiration before every API call and renewing the tokens if needed, and most API calls only return a limited number of results at a time so each time you go back that check happens again.

Thats probably too much overhead for Prowler since we have to fork several processes to implement that same check - but maybe there is a way we could force renewal before some of the long running checks?

**Comment by zfLQ2qx2** [comment]
BTW - I am asking this more from a "tell me how you want this done" perspective, I'm more than happy to take a first pass at adding force token refreshs before checks that might potentially be long running.

**Comment by jfagoagas** [comment]
Hi @zfLQ2qx2, you're totally right. This is a known issue in Prowler because as you said during long running checks the credentials could expire due to the credentials renovation is only made if necessary when the check starts to run (the code for that operation is here https://github.com/prowler-cloud/prowler/blob/master/include/execute_check#L19-L42)

The good news is that we've solved this issue in the upcoming Prowler v3, you can check it here https://github.com/prowler-cloud/prowler/tree/prowler-3.0-dev. Here is the lib in charge of the AWS authentication https://github.com/prowler-cloud/prowler/blob/prowler-3.0-dev/providers/aws/aws_provider.py

As you can see we don't use the AWS CLI anymore so we can get all the AWS SDK (Boto3) advantages like pagination, transparent authentication renewal and much more speed.

Thanks for using and contributing to Prowler!

**Comment by zfLQ2qx2** [comment]
Oh wow, this is a complete rewrite.  Probably overdue, I think you got more mileage out of the cli then anyone ever anticipated. It looks like all the check numbers got replaced with check names - is that right?

**Comment by jfagoagas** [comment]
> Oh wow, this is a complete rewrite. Probably overdue, I think you got more mileage out of the cli then anyone ever anticipated. It looks like all the check numbers got replaced with check names - is that right?

Yes, it is a complete rewrite! We have squeezed the most out of the AWS CLI.

Regarding the checks, we have [here](https://docs.google.com/spreadsheets/d/1-JA18brrg8fg7PLjrIBQtwH5qL2dZFRvgQ5-SAsE9UA/edit#gid=0) the check's roadmap and yes, check numbers has been replace for meaningful names!

I don't know if you have joined the new Prowler Slack, but if not here is the invitation link https://join.slack.com/t/prowler-workspace/shared_invite/zt-1khcj2c41-owhVxRhuNHQwZoDTKcnVlQ

Thanks @zfLQ2qx2 !!!
