### ISSUE TITLE
[Bug]: Running into 'AttributeError: 'Check_Report_AWS' object has no attribute 'status'' error

### ISSUE THREAD

**Issue by kaymaylove** [toniblyx/prowler#1575]
<img width="789" alt="Screenshot 2022-12-21 at 12 46 13 PM" src="https://user-images.githubusercontent.com/15642554/208970692-8d21afac-0205-42f7-9c03-9152e39506bb.png">

**What happened?**
I tried running ```prowler aws -f us-east-1 ```

**How to reproduce it**
1. Follow the directions here: https://pypi.org/project/prowler-cloud/

**Comment by jfagoagas** [comment]
Hi @kaymaylove, thanks for using Prowler v3!

We're checking the issue you have and we can't reproduce it. Could you please execute `prowler aws -f us-east-1 --log-level DEBUG --log-file $(date +%F).log` and send us the log file?

Please hide any sensitive information.

Thanks again!

**Comment by randomperson12365** [comment]
Hi! I also have the same issue, installed a new version via "pip install prowler-cloud".
![image](https://user-images.githubusercontent.com/108479337/209101450-3466465c-abae-4d7d-9fb3-445611dedf34.png)

**Comment by jfagoagas** [comment]
Hi @kaymaylove @kmurzin can you test it using the following branch `PRWLR-1176-bug-running-into-attribute-error-check-report-aws-object-has-no-attribute-status-error-1575`?

Right now we can't reproduce it in our environments but maybe it's due to a check failing to instantiate the `Check_Report_AWS` class.

If you can, set the `--log-level DEBUG --log-file $(date +%F).log` and send us the log file.

Thanks!

**Comment by JonoB** [comment]
Confirming fixed for me - thanks!
