### ISSUE TITLE
CSV output no longer has TITLE_ID for CIS

### ISSUE THREAD

**Issue by jsherm-fwdsec** [toniblyx/prowler#1664]
**Is your feature request related to a problem? Please describe.**
The CSV output used to include the TITLE_ID for the AWS CIS benchmarks.

**Describe the solution you'd like**
Include the CIS benchmark ID so it can be referenced from the CSV output.

**Comment by n4ch04** [comment]
Hi @jsherm-fwdsec in prowler v3  we have implemented compliance using a different flow. To launch a CIS scanning please check this out  `prowler aws --compliance cis_1.5_aws`

**Comment by jsherm-fwdsec** [comment]
Thanks @n4ch04. That's how I ran the CIS scan, using a command similar to the one you've provided. I think I understand the intention, which is to completely separate the Prowler checks from compliance, by not having anything CIS-related in the results. It might be useful to add an option to include the CIS information along with the results of each check, since some users like to see which CIS item is associated with a check.

**Comment by n4ch04** [comment]
Hi @jsherm-fwdsec right now we have that information split in the two output formats to allow us to provide more details about the results and the compliance info depending on the approach. 

If you want to correlate both formats I suggest to use a "table" approach using the check id as primary and foreign key for the different outputs.

At this moment we have not planned some kind of merge of the two outputs methods since the information from one can be easily referenced from another. I hope this trick could help you to map the info between the two formats.

Thank you for using Prowler!!
