### ISSUE TITLE
[Bug]: [extra760] Find secrets in Lambda function code is showing critical findings in output without exposing any secrets in lambda

### ISSUE THREAD

**Issue by anuj1366** [toniblyx/prowler#1760]
**What happened?**
We have run prowler for one of our production account and found one below critical findings:
**Check Title :** [extra760] Find secrets in Lambda function code.
**Risk:** The use of a hard-coded password increases the possibility of password guessing. If hard-coded passwords are used; it is possible that malicious users gain access through the account in question.
**Remediation:** Use Secrets Manager to securely provide database credentials to Lambda functions and secure the databases as well as use the credentials to connect and query them without hardcoding the secrets in code or passing them through environmental variables. 

We have analyzed our lambda code and environment variable and found like we have not hard-coded any DB/password credentials in our lambda code instead we are fetching DB credentials from Secret Manger.
We have configured below environment variable in Lambda:
** RDS_secrets_name   :    config/database_credentials **
Inside Lambda code we have called below secret manger API to fetch the real DB credentails
**secret_name = os.environ['RDS_secrets_name']
response = secretmanager.get_secret_value(SecretId=secret_name)**

**But this can not be a critical issue as we are not exposing anything in our lambda code, Please provide your input on this and fix this type of findings in prowler result.**

**How to reproduce it**
1. Run the prolwer
2. Analyze the results :: [extra760] Find secrets in Lambda function code.

**Expected behavior**
Prowler result should not consider this as critical issue.

**Screenshots or Logs**
<img width="1467" alt="image" src="https://user-images.githubusercontent.com/91662053/214228260-df228705-3ab8-4997-98fa-0ea833a976e6.png">

**From where are you running Prowler?**
Please, complete the following information:
 - Resource: EC2 instance
 - OS: Amazon Linux 2
 - Prowler Version : 2.12.0
 - Following this document

**Comment by n4ch04** [comment]
Hi @anuj1366, like you say, it seems to be a false positive, since it detects the load of a secret using an env variable as a secret. 
For the secrets detection checks Prowler relies on  detect-secrets package (https://pypi.org/project/detect-secrets/) so in your case I'll give it a try launching the package against your lambda by itself to see if detects something else, just for checking.
Regarding the false positive in the check, since we can't tune the check to avoid false positives if we do not know the content of the lambdas prior the launching of the check (and we rely on a external package), we encourage you to use the allowlist feature to include that lambda and check. 
The inclusion in the allowlist will label that as WARNING not generating the FAIL.
Also, we recommend you to start using Prowler v3, which solves a lot issues and has a huuuge performance improvement.

Thanks for using Prowler !!

**Comment by n4ch04** [comment]
Hi @anuj1366 since we don't receive any feedback from your side we consider that the issue is solved, please, if the issue persist feel free to reopen or create a new one.

Thanks for using Prowler !!
