### ISSUE TITLE
[Bug]: Deleted IAM user still raise errors

### ISSUE THREAD

**Issue by roisec** [toniblyx/prowler#2008]
Hi,
I am using the latest Prowler version.
For example, I have an IAM user that has not rotated the access key within 90 days.
When I delete the IAM user permanently, I repeatedly run the prowler again and still see the same errors for deleted IAM user...
Do you think it's a bug or have I missed something?

**Comment by n4ch04** [comment]
Hi @roisec, 

That is due to the credential report generation period, which by default is 4 hours. Prowler uses the credential report to get that information, if you change something and the credential report is not yet regenerated it will use the old credential report.

You need to wait until a new credential report is generated taking into account the changes.

Please, for the next issues fill the PR template since it helps us a lot to identify what is failing in Prowler
