### ISSUE TITLE
Ingress from internet - security group not used 

### ISSUE THREAD

**Issue by roisec** [toniblyx/prowler#2069]
Hi,
The following checks are not validating if these security groups are assigned to ENI-(network interface).
[ec2_securitygroup_allow_ingress_from_internet_to_any_port]
[ec2_securitygroup_allow_ingress_from_internet_to_port_mongodb_27017_27018]
[ec2_securitygroup_allow_ingress_from_internet_to_tcp_ftp_port_20_21]
[ec2_securitygroup_allow_ingress_from_internet_to_tcp_port_22]
[ec2_securitygroup_allow_ingress_from_internet_to_tcp_port_3389]
[ec2_securitygroup_allow_ingress_from_internet_to_tcp_port_3389]
[ec2_securitygroup_allow_ingress_from_internet_to_tcp_port_cassandra_7199_9160_8888]
[ec2_securitygroup_allow_ingress_from_internet_to_tcp_port_elasticsearch_kibana_9200_9300_5601]
[ec2_securitygroup_allow_ingress_from_internet_to_tcp_port_kafka_9092]
[ec2_securitygroup_allow_ingress_from_internet_to_tcp_port_memcached_11211]
[ec2_securitygroup_allow_ingress_from_internet_to_tcp_port_mysql_3306]
[ec2_securitygroup_allow_ingress_from_internet_to_tcp_port_oracle_1521_2483]
[ec2_securitygroup_allow_ingress_from_internet_to_tcp_port_postgres_5432]
[ec2_securitygroup_allow_ingress_from_internet_to_tcp_port_redis_6379]
[ec2_securitygroup_allow_ingress_from_internet_to_tcp_port_sql_server_1433_1434]
[ec2_securitygroup_allow_wide_open_public_ipv4]

I am suggesting adding a sub-rule for these checks to validate they use ENI and I think it will be very valuable for everyone.
There is also another check that validates if the security group is not used - [ec2_securitygroup_not_used].

**Comment by toniblyx** [comment]
Hi @roisec, you are right, those checks don't look if security groups are assigned, however, in the ephemeral world of cloud computing that is not actually necessary since a security group can be in use temporarily if it protects a Fargate task, a lambda function, part of an auto-scaling group, etc. That is the reason to have that behavior otherwise Prowler would avoid checking security groups that are eventually in use that generate a false negative which is way more dangerous than a false positive.

**Comment by n4ch04** [comment]
Hi @roisec,

Since we do not receive feedback from your side we assume that you agree with the Prowler's approach in this case.
If you need something else, please let us know creating a new issue o reopening this.

Thanks for using Prowler !!!
