### ISSUE TITLE
[Bug]: Custom policy showing warnings during creation 

### ISSUE THREAD

**Issue by cyberresearch-us** [toniblyx/prowler#2158]
### Steps to Reproduce

Using the the custom policy [prowler-additions-policy.json](https://github.com/prowler-cloud/prowler/blob/master/permissions/prowler-additions-policy.json), AWS gives the warning "This policy defines some actions, resources, or conditions that do not provide permissions. To grant access, policies must have an action that has an applicable resource or condition." 

I go back to look at the visual editor (instead of JSON) and see there are a couple warnings:
- Systems Manager - When I expand the fields down to the document field, it says "Specify document resource ARN for the GetDocument action."
- API Gateway V2 - Exapnding down to resources field, scrolling down to "Resource" field, it has "arn:aws:apigateway:*::/restapis/*" in the edit box and has "One or more actions may not support this resource."

I am not too worried about the API Gateway V2 resource as that is likely addressed with the "API Gateway" resource. I am concerned that not specifying the "document resource ARN for the GetDocument action" will cause a gap in the report. 

Should the box be checked for "Any in this account"?

### Expected behavior

I have not tested this since this is the first time I have used it. I do not know what the expected behavior is.

### Actual Result with Screenshots or Logs

![Screen Shot](https://user-images.githubusercontent.com/119474418/229248447-5a53b5bb-56c2-4858-8094-e1a41ea73c3f.png)

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

Workstation

### OS used

Windows

### Prowler version

3.2.1

### Pip version

NA

**Comment by jfagoagas** [comment]
Hi @cyberresearch-us, this is curious since the visual editor creates the following policy if you specify all resources for the `ssm:GetDocument`:

![Screenshot 2023-04-03 at 11 09 45](https://user-images.githubusercontent.com/16007882/229465038-bd67afd7-ef20-4c88-9500-cd8ccc0acc2b.png)

![Screenshot 2023-04-03 at 11 09 51](https://user-images.githubusercontent.com/16007882/229465048-b4d1781b-93a0-43c7-96e4-a3b332220a9f.png)

I think that for some reason is not being able to parse the Prowler addition policy but as far as I know this is the right permission for our checks.

Regarding the API Gateway v2 is exactly as you said, the resource is the one we need for the audit.

Thanks for using Prowler! 🚀

**Comment by jfagoagas** [comment]
Hi @cyberresearch-us, we're closing this issue since there is no possible action from our side. If you can provide us more information about this issue, please feel free to reopen it. 

Thank you for using Prowler 🚀
