### ISSUE TITLE
[Bug]: prowler: error: argument provider: invalid choice: 'gcp' (choose from 'aws', 'azure')

### ISSUE THREAD

**Issue by OsamaMahmood** [toniblyx/prowler#2199]
### Steps to Reproduce

Trying to using Prowler to do security assessment for GCP as its mentioned in the documentations and in the master branch code as well but when i run prowler with GCP argument i get error that invalid choice.

### Expected behavior

As an expected result it should take the credentials file and start the scan

### Actual Result with Screenshots or Logs

<img width="661" alt="image" src="https://user-images.githubusercontent.com/12585224/231445332-5885f846-001c-44f2-9b82-1a9fc4494ce9.png">

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

MacOS

### OS used

MacOS

### Prowler version

3.3.4

### Pip version

23.0.1

**Comment by jfagoagas** [comment]
Hi @OsamaMahmood, GCP provider is not currently available in the latest Prowler release [3.3.4](https://github.com/prowler-cloud/prowler/releases/tag/3.3.4) since just the latest fixes were included in that patch release but we will cut a new minor version soon with the latest features included.

To use GCP please clone the Github repository using `master` branch or pull the `toniblyx/prowler:latest` container image from DockerHub.

Thanks for using Prowler 🚀
