### ISSUE TITLE
Missing the criticality or severity of the check from The AWS Foundational Security Best Practices standard csv

### ISSUE THREAD

**Issue by cjmoore7** [toniblyx/prowler#2456]
### New feature motivation

When generating the report using --compliance aws_foundational_security_best_practices_aws there is no column that represents the severity of the finding [low, medium, high, critical].  

### Solution Proposed

Add a column after Status, that indicates the criticality or severity of the check performed.  

### Describe alternatives you've considered

Currently it is a manual process to add in the severity column and time consuming to have to look up each checks severity

### Additional context

This check would be helpful for all compliance generated reports, not just the aws_foundational_security_best_practices_aws

**Comment by toniblyx** [comment]
Hi @cjmoore7 thanks for giving a try to that recently added framework. As you can see in any other compliance framework in Prowler, we don't add severity because that is always part of the framework itself, it is per requirement, not based on every Prowler check (since a requirement in compliance can be one or multiple checks). For the Well Architected Framework Security pillar they have something called LevelOfRisk that can be used like severity. Additionally, remember that when you run that compliance framework you get the default Prowler output so you can mach checks from the default output with those checks and requirements of the framework you use.

**Comment by cjmoore7** [comment]
Thank you for your update, that makes a lot of sense, I can provide my clients with that level of detail.
