### ISSUE TITLE
[Bug]: Memory leakage in aws lambda scanning mechanism 

### ISSUE THREAD

**Issue by Moshikol** [toniblyx/prowler#2516]
### Steps to Reproduce

Run prowler on an aws account with large amount of lambda functions.
The command we used to run prowler python package
`prowler aws --severity critical high -M json -o . -F output --quiet --filter-region us-east-1`

### Expected behavior

Prowler will run and finish the scan and provide findings.

### Actual Result with Screenshots or Logs

The system has terminated Prowler's process due to extensive memory usage.

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

Docker container on AWS Fargate

### OS used

Python 3.9 Docker image

### Prowler version

3.5.1

### Pip version

pip 23.01

### Context

**Issue Description:**
We encountered Prowler process being killed by the system (docker container) and exiting with -9 status code, which happened on large-scale aws users which a large amount of lambda functions in their AWS accounts.
**What we tried:**
- Increasing the file descriptors.
- Increasing the CPUs and memory of the container.  

After investigating the code of the `awslambd` service of Prowler, we found out the logic of this service is zipping all of the lambda functions codes in `self.functions` Lambda class property.
This situation results in a memory overload when there are a lot of lambda functions in the scanned account.
here is a screenshot of the code snippet:
![image](https://github.com/prowler-cloud/prowler/assets/19548879/8c7cadba-3455-41ba-886c-6e679d3eeff6)

**Comment by jfagoagas** [comment]
Hi @Moshikol, this is a known issue of the `awslambda` service that happens if you execute the `awslambda_function_no_secrets_in_code` check as you can see here:
https://github.com/prowler-cloud/prowler/blob/435911489f31b84246bd090984877f08bda69305/prowler/providers/aws/services/awslambda/awslambda_service.py#L32

We have planned to improve this code just to clean each Lambda upon execution but for now I recommend you to exclude the check using the following flag:
`--excluded-checks awslambda_function_no_secrets_in_code`

Thanks for using Prowler 🚀

**Comment by jfagoagas** [comment]
Hi @Moshikol, we're closing this issue. Please feel free to reopen it if you notice the same behaviour again or you can provide us additional information.

Thanks for using Prowler 🚀
