### ISSUE TITLE
Criteria (PASS/FAIL) for each inspection item in Prowler v2, v3

### ISSUE THREAD

**Issue by kimdoyoung0430** [toniblyx/prowler#2681]
### New feature motivation

Is there any data that summarizes the difference in inspection criteria between Prowler v3 and v2?
The more detailed it is, the better.
Where can I see the comparison data for each item?

### Solution Proposed

 the difference in inspection criteria between Prowler v3 and v2

### Describe alternatives you've considered

The more detailed it is, the better.

**Comment by jfagoagas** [comment]
Hi @kimdoyoung0430, unfortunately we don't have that comparison but as an overall answer to your question we have fixed the inspection criteria issues from v2. Prowler v3 is a complete refactor in Python 3 to have a better, faster and reliable version.

Apart from that, if you have specific questions about changes you notice please ask us.

Also, refer to the public documentation at https://docs.prowler.cloud

Thanks for using Prowler 🚀

**Comment by Jaeyoon32** [comment]
Hi @jfagoagas, I have further questions. 
Let's assume that there is a check ID which is checkXXX for v2 and checkYYY for v3 and they are matched each other. Is it guaranteed that inspection criteria on v2 script and v3 python file are identical?
Since we already have made custom remediation guides based on Prowler v2, we want to know that the same guides could be used if we use Prowler v3 as long as a check ID is same on both versions.

**Comment by jfagoagas** [comment]
Hi @Jaeyoon32, the answer is yes but for some checks we've refactored the logic to improve and to have more accurate findings.

In the following section https://docs.prowler.cloud/en/latest/tutorials/aws/v2_to_v3_checks_mapping/ you can check the translation from v2 to v3 because some v2 checks were combined into one v3 check

**Comment by jfagoagas** [comment]
Hi @Jaeyoon32 @kimdoyoung0430 was I able to solve the questions you had about the differences between Prowler v2 and v3?

**Comment by kimdoyoung0430** [comment]
Hi, @jfagoagas 
I checked with Prowler docs document. However, when performing v2 and v3, it is necessary to verify the inspection results.

**Comment by jfagoagas** [comment]
Yes, we fixed issues coming from the V2.

**Comment by jfagoagas** [comment]
Hi @kimdoyoung0430 @Jaeyoon32, I think it'll be great if you can join our Slack https://join.slack.com/t/prowler-workspace/shared_invite/zt-20jrnt2m9-34~lxJeL9VgZzacy2Gt_Jw because it's a better place to discuss and ask questions like this.

Thanks for using Prowler 🚀

**Comment by kimdoyoung0430** [comment]
Thank you for your reply.
