### ISSUE TITLE
[Bug]: Authorization Issue with AWS provider

### ISSUE THREAD

**Issue by akshaypawartw** [toniblyx/prowler#2830]
### Steps to Reproduce

Command executed from local desktop - Prowler aws

Prowler version - 3.9.0

The user created in aws iam has no permission attached to it, for running scan the user needs following permissions as mentioned in documentation (SecurityAuditUser, ViewOnlyAccess, Custom Policy).
But the user I created in my aws account has no permission attached please find below screenshot.
![image](https://github.com/prowler-cloud/prowler/assets/143079916/5d552492-19a2-4f8a-a53b-403cb6333db9).
Still the Prowler scan works on my local desktop.

### Expected behavior

Authorization should fail due to lack of permissions

### Actual Result with Screenshots or Logs

![0D7B778F-5A46-4F4D-B634-2B5A17A1C0D9](https://github.com/prowler-cloud/prowler/assets/143079916/708e270a-26f4-43c3-a794-d346c890f395)

### How did you install Prowler?

From brew (brew install prowler)

### Environment Resource

Workstation

### OS used

MacOS

### Prowler version

3.9.0

### Pip version

NA

**Comment by jfagoagas** [comment]
Hi @akshaypawartw Prowler does not fail if the entity used to audit has not permissions at all since you can audit specific services, regions, resources using an entity with restricted permissions. If the entity used has no permissions Prowler will raise several logs with the `ERROR` level showing that the API call made to the provider failed due to a lack of permissions.

Thanks for using Prowler 🚀
