### ISSUE TITLE
check one rule is very slow

### ISSUE THREAD

**Issue by ripperi8u** [toniblyx/prowler#3041]
### New feature motivation

When i just want to check the rule of "ec2_securitygroup_not_used", prowler process will cost much time,because the __init__ function of class "EC2" in file ec2_service.py will call many functions,such as "__describe_instances__"、"__describe_network_acls__", and they are useless for rule of "ec2_securitygroup_not_used"

### Solution Proposed

just init the resources with function calls when the checking rules need, and it will lessen much time

### Describe alternatives you've considered

according to the checking rules,determine the minimal resources should be initialized,the useless resources should not be initialized

**Comment by jfagoagas** [comment]
Hi @ripperi8u, due to the Prowler v3 design all services are instantiated before executing a check, to be available for all the checks using that service. Also, some checks uses different services like the `ec2_securitygroup_not_used` check which uses the `EC2` and `Lambda` services, so in this version we cannot just call some functions based on the check needs since there is no way to do it dynamically, and having a definition with checks and functions could end up in stale versions and more manual management.

For the next major version of Prowler we are thinking about a new way to instantiate services based on the information the check need for its execution.

We appreciate your feedback.

Thanks for using Prowler 🚀
