### ISSUE TITLE
[Bug]: apigateway_restapi_authorizers_enabled.py does not consider authorizers configured at the method level

### ISSUE THREAD

**Issue by Fennerr** [toniblyx/prowler#3082]
### Steps to Reproduce
```
prowler -s apigateway
```
### Expected behavior

Prowler produces a false positive (kind of) when there isnt a authorizer enabled at at the rest api level - but all the methods in the rest api had an authorizer configured

### Actual Result with Screenshots or Logs

![Screenshot from 2023-11-30 17-05-22](https://github.com/prowler-cloud/prowler/assets/41741346/26c2f9c0-913b-4d6e-b947-fb5bd5637bdc)

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

Local instance (kali)

### OS used

Debian-based (kali)

### Prowler version

Prowler 3.11.3 (You are running the latest version, yay!)

### Pip version

pip 23.3

**Comment by n4ch04** [comment]
Hi @Fennerr,
It makes sense, since the check metadata explicitly specifies `If no authorizer is enabled anyone can use the service.`  so authorization can be handled at API scope or method scope.  
I think I'm gonna store the method configuration in the `apigateway` service, and then the check logic would be:
```
if rest_api.authorizer:
    report.status = "PASS"
elif all methods authorized:
   report.status = "PASS"
else:
   report.status = "FAIL"
```

If a single method is not authorized and there is no API authorizer configured it would generate a `FAIL`

What do you think?

**Comment by n4ch04** [comment]
Please @Fennerr test the proposed solution and let us know if it works

**Comment by Fennerr** [comment]
Hi @n4ch04 - this does seem like a good approach - the only thing I would add is maybe skipping authorization checks on OPTIONS calls. Im a bit busy today, but Ill give it a go tomorrow and report back

**Comment by n4ch04** [comment]
Ok, please check it and let us know, we can add the `OPTIONS` http method handling
