### ISSUE TITLE
[Bug]: Empty fields (["resources"][0]["region"] and ["finding"]["types"]) in json ocsf result when the target is an Azure account

### ISSUE THREAD

**Issue by rvisc** [toniblyx/prowler#3532]
### Steps to Reproduce

/usr/local/bin/prowler azure --log-level ERROR --sp-env-auth -M json-ocsf -o . -F prowler_scan_results -z

### Expected behavior

I expected the ["resources"][0]["region"] and ["finding"]["types"] fields to contain values.

### Actual Result with Screenshots or Logs

The ["resources"][0]["region"] field always results in an empty string ("").
The ["finding"]["types"] field always results in an empty list ([]).

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

Docker container locally

### OS used

Debian GNU/Linux 11 (bullseye)

### Prowler version

3.14.0

### Pip version

22.2.2

### Context

![Azure json ocsf result](https://github.com/prowler-cloud/prowler/assets/75303078/0eeed357-8593-4491-b9f2-285e5cfbda9e)

**Comment by jfagoagas** [comment]
Hi @rvisc, currently we are working on the new version of the OCSF schema 1.1.0 since the 1.0.0 version, the one implemented in Prowler v3, has been deprecated. In that version those fields are filled with data coming from the Azure findings. If you want to see the current development please take a look at https://github.com/prowler-cloud/prowler/blob/dbc232a631d349718725ac6c26fc5d86f40fafdf/prowler/lib/outputs/json_ocsf/json_ocsf.py#L33

We will publish soon a new Prowler version with the OCSF 1.1.0 with the new [Detection Finding](https://schema.ocsf.io/1.1.0/classes/detection_finding?extensions=) instead of the [Security Finding](https://schema.ocsf.io/1.1.0/classes/security_finding?extensions=).

Thanks for using Prowler 🚀

**Comment by jfagoagas** [comment]
Hi @rvisc, we've just released [Prowler v4](https://github.com/prowler-cloud/prowler/releases/tag/4.0.0) which uses OCSF v1.1.0 as the JSON output. I'm closing this issue, please feel free to reopen it if you encounter the same issue again. Please upgrade using `pip install prowler --upgrade`.

Thanks for using Prowler 🚀
