### ISSUE TITLE
[Bug]: exit code > 0 if there are muted failures (version 4.0)

### ISSUE THREAD

**Issue by jansepke** [toniblyx/prowler#3721]
### Steps to Reproduce

I try to reproduce the setup we had in v3 where a muted failure would not trigger an exit code > 0.
this is the command we are using in v4
```
prowler aws \
      --verbose --status FAIL \
      --mutelist-file prowler-mutelist.yaml 
```

### Expected behavior

Do not exit with exit code > 0 if there are only muted failures. Comparable to this command in v3
```
prowler aws \
      --verbose --quiet \
      --allowlist-file prowler-allowlist.yaml
```

### Actual Result with Screenshots or Logs

![image](https://github.com/prowler-cloud/prowler/assets/625043/37db7c83-92b4-429c-8a1f-b67d6ace2c5a)

with exit code > 0

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

-

### OS used

-

### Prowler version

4.0

### Pip version

-

**Comment by MrCloudSec** [comment]
Hi @jansepke , thanks for reaching us out!
Can you execute it again with `--log-level ERROR` to see if there is any error in the mutelist logic?

**Comment by christiandavilakoobin** [comment]
Hi,

Same problem here. I just executed with the --log-level ERROR, and I saw this:

```
2024-04-10 08:59:10,693 [File: backup_service.py:128]   [Module: backup_service]         ERROR: eu-south-2 -- ClientError[103]: An error occurred (AccessDeniedException) when calling the ListReportPlans operation: Insufficient privileges to perform this action.
```

The role has privileges to access the backup:ListReportPlans, but I think the problem is that this action doesn't exists on eu-south-2. Using an admin account and the aws cli, I have this output:
```
$ aws --region eu-west-1 backup list-report-plans
{
    "ReportPlans": []
}

$ aws --region us-east-1 backup list-report-plans
{
    "ReportPlans": []
}

$ aws --region eu-south-2 backup list-report-plans

An error occurred (AccessDeniedException) when calling the ListReportPlans operation: Insufficient privileges to perform this action.
```

Also, results are a bit confusing, as it says "NO_CUMPLE", but all fails are muted.

![image](https://github.com/prowler-cloud/prowler/assets/46561103/3938c83b-60ba-4432-b0a4-34f571e53800)

**Comment by pedrooot** [comment]
Hi! @christiandavilakoobin  thanks for the report, we will review it and we'll get back to you soon.
Thanks for using Prowler! 😁

**Comment by jfagoagas** [comment]
Hi @jansepke, I find the issue you are having. In v4 the original status, `PASS`, `FAIL` or `MANUAL`, is kept alongside with the `muted` field, so:
- v3: One or more findings with a `FAIL` status regardless of the number of `WARNING` status triggers the exit with the status code 3. All findings as `WARNING` makes the exit with status code 0.
- v4: Since the `muted` is just an extra field, if there is one `FAIL` finding the exit code will be 3.

I think in v4 we have to check if all the `FAILS` are `muted` to do an exit code 0, am I right?

**Comment by jfagoagas** [comment]
Hi @jansepke I think I fixed the issue in the above PR, could you give it a try and let us know if this fixes it? Thanks!

The branch is `PRWLR-3492-prowler-bug-exit-code-0-if-there-are-muted-failures-version-4-0`.

**Comment by pedrooot** [comment]
Hey! @christiandavilakoobin related to Muted Failures/Pass I think I fixed it in the branch `bug-3721`
Let us know if it works correctly, thanks!

**Comment by jansepke** [comment]
@jfagoagas yes, I tried that branch and the exit code is now 0 as expected. thank you, can you release that please :+1:

**Comment by jfagoagas** [comment]
Great! We'll try to cut a new release today, if not on Monday. Thanks @jansepke

**Comment by jfagoagas** [comment]
@christiandavilakoobin we've merged the [PR](https://github.com/prowler-cloud/prowler/pull/3751) to fix the compliance output with muted findings.

I'm closing this issue, please feel free to reopen it if notice a different behaviour. Thanks for using Prowler 🚀

**Comment by christiandavilakoobin** [comment]
Thanks @jfagoagas ! I'll try as soon as I can, and I'll reopen if something is wrong!

**Comment by jansepke** [comment]
@jfagoagas could you please release a new version that includes this fix?

**Comment by jfagoagas** [comment]
@jansepke we will release a new version this week but we are finish work for it.
