### ISSUE TITLE
[Bug]: HTML report format Prowler v4

### ISSUE THREAD

**Issue by christiandavilakoobin** [toniblyx/prowler#3725]
### Steps to Reproduce

Execute prowler and ask to generate the report in HTML format, as it says on docs https://docs.prowler.com/projects/prowler-open-source/en/latest/tutorials/reporting/#html.

```
prowler aws -M html
```

### Expected behavior

Generate a html file report.

### Actual Result with Screenshots or Logs

Prowler says:
```
prowler aws: error: argument --output-formats/--output-modes/-M: invalid choice: 'html' (choose from 'csv', 'json-asff', 'json-ocsf')
```

### How did you install Prowler?

Docker (docker pull toniblyx/prowler)

### Environment Resource

3. Docker container

### OS used

5. Ubuntu

### Prowler version

4.0.0

### Pip version

the one on official prowler docker image

**Comment by jfagoagas** [comment]
Hi @christiandavilakoobin, the HTML output has been deprecated in Prowler v4. We are currently updating all the Prowler Open Source documentation to reflect those changes. In the release notes all the breaking changes are present https://github.com/prowler-cloud/prowler/releases/tag/4.0.0. 

We made that decision since now we have a new local dashboards where you can get much more from you Prowler outputs, please refer here to get more information about it https://docs.prowler.com/projects/prowler-open-source/en/latest/tutorials/dashboard/.

Thanks for using Prowler 🚀

**Comment by christiandavilakoobin** [comment]
Hi @jfagoagas! Thanks for the response. I'm trying to use the dashboard, but it doesn't work. It says it's running, but it didn't response anything:
```
Dash is running on http://127.0.0.1:11666/
```

![image](https://github.com/prowler-cloud/prowler/assets/46561103/3bd89881-e5d3-41b3-88b9-225a694a8fde)

**Comment by jfagoagas** [comment]
@christiandavilakoobin, the dashboard component runs on localhost by default. You can use the following command to expose it: `docker run -e HOST=0.0.0.0 -p 11666:11666 toniblyx/prowler:latest dashboard`, **remember that the `dashboard` server is not authenticated so you are exposing it at your own risk.**

Thanks!

**Comment by christiandavilakoobin** [comment]
I added the HOST env var, as you suggested (the port I've already did), and it works! 

Thanks!
