### ISSUE TITLE
Check28 Fails despite key rotation activated 

### ISSUE THREAD

**Issue by oliviermtl** [toniblyx/prowler#4123]
### Steps to Reproduce

Prowler Version: 2.12.0-27October2022
Parameters used: -M text,junit-xml,html,csv,json -g cislevel2 -w arn:aws:dynamodb:ap-southeast-1:804479693801:table/prowler_allow_list

### Expected behavior

Should not fail

### Actual Result with Screenshots or Logs

<img width="289" alt="Screenshot 2024-05-29 at 14 52 03" src="https://github.com/prowler-cloud/prowler/assets/90613/0d9edb05-5ace-4f5d-8f4d-85acb7b163cb">
<img width="364" alt="Screenshot 2024-05-29 at 14 52 21" src="https://github.com/prowler-cloud/prowler/assets/90613/df2fe98b-73ff-40ba-a3e0-fd71eb787138">

### How did you install Prowler?

Docker (docker pull toniblyx/prowler)

### Environment Resource

Fargate task

### OS used

Amzon Linux 2

### Prowler version

2.12.0-27October2022

### Pip version

?

**Comment by jfagoagas** [comment]
Hi @oliviermtl I see that you are using Prowler v2 which is out of support as of today. We released Prowler v3 more than a year ago now and I recommend you to upgrade to the latest version of Prowler, which was released yesterday https://github.com/prowler-cloud/prowler/releases/tag/4.2.0, to take advantage of all the new checks, visualizations and fixes we included in Prowler since v2.

You can install the latest version of Prowler following this documentation https://docs.prowler.com/projects/prowler-open-source/en/latest/#installation. Then you can run:
```
prowler aws \
    --output-modes html json-ocsf csv \
    --check kms_cmk_rotation_enabled \
    --mutelist-file arn:aws:dynamodb:ap-southeast-1:804479693801:table/prowler_allow_list
```

Please, let me know if this works fine for you.

Thanks for using Prowler 🚀 

Join our Slack workspace using this invite https://join.slack.com/t/prowler-workspace/shared_invite/zt-2j7ot11wn-0DlRMtyNaEZ~f9mv4oU9Jg where we provide support and guidance and we have a great community about Prowler.

**Comment by jfagoagas** [comment]
Hi @oliviermtl have you been able to check the above comment? Thanks!

**Comment by jfagoagas** [comment]
Hi @oliviermtl I'll close this issue. Please feel free to reopen it or reach out to us if this doesn't work for you.

Thanks for using Prowler 🚀
