### ISSUE TITLE
Cannot import name 'SerializationError' from 'azure.core.exceptions' (/usr/lib/python3/dist-packages/azure/core/exceptions.py)

### ISSUE THREAD

**Issue by Raafay892** [toniblyx/prowler#4529]
### Steps to Reproduce

python3 prowler.py azure
![image](https://github.com/user-attachments/assets/2e20d648-b473-4498-8285-ba7df19f11f2)

### Expected behavior

![image](https://github.com/user-attachments/assets/050ca7c2-f7d5-4d4d-ae36-a54f75879b68)

### Actual Result with Screenshots or Logs

![image](https://github.com/user-attachments/assets/d2b75d10-6f4d-4496-a710-0599d4993310)

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

locally on red cloud OS

### OS used

red cloud OS

### Prowler version

4.2.4

### Pip version

24.1.1

**Comment by puchy22** [comment]
Hi @Raafay892,

It appears that you're encountering a dependency issue. Please follow the [Prowler installation documentation](https://docs.prowler.com/projects/prowler-open-source/en/latest/#__tabbed_1_4) for guidance.

Since it looks like you're using the GitHub installation method, try running the `poetry install` command to complete the dependency installation.

If you continue to experience issues, please share the error message you're receiving, and I'll be happy to assist further.

Thank you for using Prowler!

**Comment by Raafay892** [comment]
okay sure

**Comment by puchy22** [comment]
Hi @Raafay892,

As there has been no response in over a week, I will be closing this issue for now. If you need further assistance, feel free to reopen it.

Thank you for using Prowler 🚀
