### ISSUE TITLE
Slack integration for critical medium high low mute alerts 

### ISSUE THREAD

**Issue by codepipe** [toniblyx/prowler#4843]
### New feature motivation

Slack integration including the list of findings instead of just the aggregates.

### Solution Proposed

When it scans EC2 suppose, it should send critical alerts which EBS volume is not encrypted and it should the points also
like this all the services.

### Describe alternatives you've considered

N/A

### Additional context

```
Hey there :wave:
I'm Prowler, the handy multi-cloud security tool :cloud::key:
I have just finished the security assessment on your AWS Account 809847124973 with a total of 262 findings.
- 206 Passed findings (78.63%)
- Failed findings (21.37%)
- 81 Scanned Resources

<Add list of findings>
```

**Comment by codepipe** [comment]
Hey there :wave:
I'm Prowler, the handy multi-cloud security tool :cloud::key:
I have just finished the security assessment on your AWS Account 809847124973 with a total of 262 findings.
206 Passed findings (78.63%)
Failed findings (21.37%)
 81 Scanned Resources
 
 i need which failed findings list example

**Comment by abant07** [comment]
Hey @jfagoagas 

While I'm waiting to get approval from @pedrooot to start working on the ingress/egress issue, can I work on this one?

Thanks,
Amogh

**Comment by pedrooot** [comment]
Sure! @abant07 go for it

**Comment by abant07** [comment]
Hey @jfagoagas @pedrooot 

Here is my plan to go about solving this issue.

Firstly, I want @codepipe to know that I believe the reason why Prowler doesn't list out all the findings for the passed and failed checks is because there are some prowler users who will have thousands of findings, and if we were to display all those findings without some sort of sorting mechanism, it will get really messy and long, and hinder the user experience. (Prowler team correct me if I am wrong on this).

However, I do believe it's important to get some insight to what findings went wrong and which ones went right. So, what I will do is I will select 20 random findings that passed and 20 random findings that failed, and list them in the slack report.

As per how I will change the code. There are two files I will be altering, the slack.py file and the outputs.py file. In the slack.py file there is a method called the `__create_message_blocks__()` and this method is responsible for creating the UI of the slack report, and this method also takes in a parameter called stats, which is a dictionary that is generated in the ouputs.py file.

In the outputs.py file, there is a method called `extract_findings_statistics` which is generating the statistic reports for each finding and then displaying it in the slack report. Currently, it generates information like total failed, total passed, total muted failed, total muted passed, resource count. 

So, what I will need to do is add another 2 key-value pair in the dictionary that the `extract_findings_statistics` method is returning called stats["findings_passed/failed"] = finding_names, where finding_names is a list of 20 random findings that were passed/failed. Then in the slack.py file, I will reference in these keys and display them as a list in the slack report.

However, I did have one question, do "findings" basically mean the check names (ie. ec2_client_vpn_endpoint_connection_logging_enabled). Because if so, in the outputs_test.py file, we are currently using MagicMock() to simulate these findings, but there are no "name" fields, just resource_id and status, or muted.

for example, here is what I mean

finding_1 = mock.MagicMock()
        finding_1.status = "PASS"
        finding_1.resource_id = "test_resource_1"
        finding_2 = mock.MagicMock()
        finding_2.status = "FAIL"
        finding_2.resource_id = "test_resource_2"
        findings = [finding_1, finding_2]

**Comment by abant07** [comment]
After thinking about it. What I can do is instead of doing 20 random passes and fails, I will only list checks that have the critical severity.
