### ISSUE TITLE
Use IAM identity to calculate threat detection threshold

### ISSUE THREAD

**Issue by 0xbadshah** [toniblyx/prowler#5057]
### New feature motivation

The current implementation of threat detection (both privilege escalation and permission enumeration) uses number of potential priv esc/enumeration attempts per source IP address. While it detects simple bruteforce from single IP, the bypass is really easy - combine pacu/iam enumerate with IP rotation tools. The threshold will stay under default threshold limit and doesn't detect the attack.

### Solution Proposed

Trying to find threshold based on IAM identity could help detect attacks. Let's say attacker uses pacu/iam enumerate with IP rotation tools, the IAM identity that the attacker uses is still the same. Using threshold based on IAM identity, prowler can find and flag the identity.

### Describe alternatives you've considered

N/A

**Comment by MrCloudSec** [comment]
Hi @Chan9390, this is a really good feedback, thank you!

We will based the threshold on the IAM identity that is doing the API calls instead of on the Source IP.

I'll let you know when the change is made so you can test it 😄

**Comment by abant07** [comment]
Hey @sergargar 

Is this issue open to contributors or is the Prowler team already on it? If not, could I work on this one?

Thanks,
Amogh

**Comment by MrCloudSec** [comment]
Hey @Chan9390, we have not started with this issue yet, so ofc is open to contributors. 

If you want you can work on this 😄 Thanks!

**Comment by abant07** [comment]
Sounds good. I will take a crack at it.

I will do what Pepe usually does.

I will first reiterate my understanding of the issue (to make sure no confusion), then I will give a semi detailed plan of what I will do in terms of changing the code.

**Comment by abant07** [comment]
Ok so I did some digging, and here is my plan @sergargar @Chan9390 

So from what I understand, CloudTrail has checks called threat detection_enumeration (which is checking for brute force attempts by looking at the times that requests were made and if the number of requests in that time frame exceeds a certain threshold that the Prowler customer sets in the configuration file) and there is threat detection_priviledge_escalation (which looks at if there are multiple requests related to granting more permissions for the requester)

Looking at the code, it seems that we are checking the ip address of the requester by using the lookup_events boto3 api and then accessing the CloudTrailEvent object, which contains the sourceIpaddress and the eventName.

one thing I would like to point out is that for the privilege escalation, the code for the check looks very similar to the enumeration code, however, I think it would be also important that in addition to checking to see if the number of requests exceed a threshold, we should have it so the check for looks at the specific requests being made to see if they are permission type requests(AttachRolePolicy, AddUserToGroup, UpdateAssumeRolePolicy, etc), otherwise the logic is very similar to enumeration, which is checking for brute force attemps for any type of event.


However, aside from that, my plan to change the code will be to edit escalation and enumeration files, so that instead of looking for sourceIP address, I will look for the userIdentity object, which specifies a unique principalID

this will be changed

`if ".amazonaws.com" not in event_log["sourceIPAddress"]:
                        if event_log["sourceIPAddress"] not in potential_enumeration:
                            potential_enumeration[event_log["sourceIPAddress"]] = set()
                        potential_enumeration[event_log["sourceIPAddress"]].add(
                            event_name
                        )
`

with the principalID attribute from this object.
`
"userIdentity": {
        "type": "AssumedRole",
        "principalId": "AROATZZZ4JPIXUEXAMPLE:EXP21nT17WMzA6dnUgz",
        "arn": "arn:aws:sts::111122223333:assumed-role/AllowActions/EXP21nT17WMzA6dnUgz",
        "accountId": "111122223333",
        "accessKeyId": "AKIAI44QH8DHBEXAMPLE",
        "sessionContext": {
            "sessionIssuer": {
                "type": "Role",
                "principalId": "AROATZZZ4JPIXUEXAMPLE",
                "arn": "arn:aws:iam::111122223333:role/AllowActions",
                "accountId": "111122223333",
                "userName": "AllowActions"
            },
            "webIdFederationData": {},
            "attributes": {
                "creationDate": "2022-05-30T13:23:19Z",
                "mfaAuthenticated": "false"
            }
        },
        "invokedBy": "fis.amazonaws.com"
    },
`
However, I was a bit confused on the portion in the code that checks for multi-region trails. Is there a reason why we break after iterating over the trails and detecting a multi-region trail. Is it because if we have a multi-region trail configured, it will log everything in our account, and so we don't need to consider the individual trails that are being recorded per region? Because if so, I was wondering does a user have the ability to select what regions they want to have Cloudtrail trails for when enabling cloudtrail trails?

`
potential_enumeration = {}
        found_potential_enumeration = False
        multiregion_trail = None
        # Check if any trail is multi-region so we only need to check once
        for trail in cloudtrail_client.trails.values():
            if trail.is_multiregion:
                multiregion_trail = trail
                break
        trails_to_scan = (
            cloudtrail_client.trails.values()
            if not multiregion_trail
            else [multiregion_trail]
        )
`

**Comment by MrCloudSec** [comment]
@Chan9390 sounds good!
Correct, the idea is that if there is multiregion trail we don't have to look for individual trails since the multiregional is already looking for the logs in all regions. As far as I know, you cannot select specific regions in multiregion trails, the trail will log all regions.

**Comment by abant07** [comment]
Hey @sergargar 

I believe I have figured it out and submitted a PR. However, I was a bit confused on what the difference in the code is for privilege escalation and enumeration is. The code for both of these checks look the same?

**Comment by MrCloudSec** [comment]
> Hey @sergargar
> 
> I believe I have figured it out and submitted a PR. However, I was a bit confused on what the difference in the code is for privilege escalation and enumeration is. The code for both of these checks look the same?

The only difference is on the configurable variables that each one uses.

Thanks for the PR btw, I have leave you some comments to address.

**Comment by abant07** [comment]
Sounds good. But I was curious, do you think it would be better if the privilege escalation looked at keywords in each programmatic request that was made to determine if the enumeration check should be flagged or privilege escalation?

Because from what I understand, enumeration is checking to see if an attacker is brute forcing any command to alter the state of resource like shutting off load balancing for Ec2 maybe, whereas privilege escalation is an attacker wants to obtain higher permissions so they will try to brute force permission related programmatic requests (like Updating the policy of IAM users, or creating more users, etc)

**Comment by MrCloudSec** [comment]
As far as I know, the enumeration technique is trying to check the existing resources in an environment so the attacker knows more the attacking surface, that is why we put API Calls related to listing AWS resources.

**Comment by abant07** [comment]
Ah I see, ok that make sense
