### ISSUE TITLE
Unable to generate pydantic-core schema

### ISSUE THREAD

**Issue by vishal-spektrum** [toniblyx/prowler#5518]
### Steps to Reproduce

i have system with installed fastapi which uses pydantic version == 2.9.2
which conflicts with the pydantic version ==1.10.18  which is used by prowler

which gets me the error as
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'prowler.lib.check.compliance_models.CIS_Requirement_Attribute_Profile'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

### Expected behavior

prowler should use latest version of pydantic in order for the code to work

### Actual Result with Screenshots or Logs

![Screenshot from 2024-10-24 12-59-38](https://github.com/user-attachments/assets/93392827-aa9f-4ed5-82db-e1031ff076a1)
![Screenshot from 2024-10-24 12-59-10](https://github.com/user-attachments/assets/70a97ba5-8e79-438c-b3c3-1aa5c7269e48)

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

docker containers

### OS used

ubuntu

### Prowler version

Prowler 4.2.1

### Pip version

pip 23.0.1

**Comment by MrCloudSec** [comment]
Hi @vishal-spektrum, I will discuss it internally with the team to upgrade pydantic to the latest version and I will get back to you. Thanks!

**Comment by vishal-spektrum** [comment]
> Hi @vishal-spektrum, I will discuss it internally with the team to upgrade pydantic to the latest version and I will get back to you. Thanks!

**Comment by puchy22** [comment]
Hi @vishal-spektrum, right now it is not quite clear in our roadmap when the Pydantic version will be updated, but we will try to do it as soon as possible and we will notify you about it.
In the meantime you can try the [default installation](https://docs.prowler.com/projects/prowler-open-source/en/latest/#installation) we recommend which is `pipx`. As it creates isolated environments to install Prowler and all its dependencies, it is the best practice to install packages in isolated environments otherwise you may encounter conflict problems like yours.
I hope you find this useful, let me know if this does not solve your problems.

Thank you very much for using Prowler 🚀

**Comment by puchy22** [comment]
Hi @vishal-spektrum,

Did the answer I provided work for you, or do you have any additional questions? If anything is still unclear, feel free to ask here again. If there’s no response within a week or so, I’ll consider the issue resolved.

Thank you for using Prowler!

**Comment by puchy22** [comment]
Hi @vishal-spektrum,

I am going to close this issue due no answers. If you have any related questions, please feel free to reopen it and share your comments.

Thanks for using Prowler 🚀
