### ISSUE TITLE
`finding_uid` is not unique in `iam_rotate_access_key_90_days`

### ISSUE THREAD

**Issue by banv** [toniblyx/prowler#6105]
### Steps to Reproduce

python prowler.py aws -s iam

### Expected behavior

The program output CSV file with the same finding_uid like that 
prowler-aws-iam_rotate_access_key_90_days-<AWS ACCOUNT_ID>-us-east-1-<IAM_USER>

This IAM_USER has 2 access keys

### Actual Result with Screenshots or Logs

No log

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

8. Other (Local PC)

### OS used

2. MacOS 

### Prowler version

Prowler 5.1.0 (You are running the latest version, yay!)

### Pip version

pip 23.3

### Context

The source code of [finding.py ](https://github.com/prowler-cloud/prowler/blob/master/prowler/lib/outputs/finding.py#L238-L241)

```
output_data["uid"] = (
                f"prowler-{provider.type}-{check_output.check_metadata.CheckID}-{output_data['account_uid']}-"
                f"{output_data['region']}-{output_data['resource_name']}"
            )
```

Do we need add UUID to above line to avoid problem?

**Comment by jfagoagas** [comment]
Hello @banv, that's a great catch!

The Prowler Finding UID has the above format for historical reasons and can't be an UUID since it can't be changed because it'll introduce a breaking change. I think in this case the check needs to be adjusted to add a index for each access key, like `prowler-aws-iam_rotate_access_key_90_days--us-east-1-<IAM_USER>-access-key-[0,1]`. 

With that we'll achieve uniqueness in the `finding_uid`. Let me know what you think about it.

Thanks for using Prowler! 🚀
