### ISSUE TITLE
CloudTrail check 2.3 can't be solved

### ISSUE THREAD

**Issue by kingferiol** [toniblyx/prowler#881]
Hi all

In our AWS multi-accounts setup with Control Tower, we have a critical FAIL on Cloud Trail that we can't solve in any way.

**[check23] Ensure the S3 bucket CloudTrail logs to is not publicly accessible**

In the account under investigation, we tried with the following set of commands:

1. aws cloudtrail describe-trails --query 'trailList[*].S3BucketName'
2. aws s3api get-bucket-acl --bucket <command-1-bucket> --query 'Grants[?Grantee.URI== `https://acs.amazonaws.com/groups/global/AllUsers` ]'
3. aws s3api get-bucket-policy --bucket <command-1-bucket>

We add an issue due to grants.

In the log account (where we have the trail) as an outcome of command 2, we have an empty list, and command 3 works fine (no policy with AWS:*).

Is there something that we miss to avoid the critical issue?

Thanks for the help and the great tool.

**Comment by w0rmr1d3r** [comment]
Hello @kingferiol !
What do you mean by `We add an issue due to grants.`?
At the same time, which version of Prowler are you using?

If I'm not wrong, by running your command 2 it should fall into the first conditional of:
https://github.com/toniblyx/prowler/blob/master/checks/check23#L82
and should be a PASS.
However, if the variable is an empty list, the conditional will fail since the variable is set to something (a list in your case) (if I'm not wrong about bash -z conditionals).
Can you try running that check only like so?
```bash
bash -x ./prowler -c check23
```

You should see the actual value for that
If it's something like:
```
+ CLOUDTRAILBUCKET_HASALLPERMISIONS=
++ echo ''
```
It should be a pass, if not, put here the output and we'll take a look!

Thank you!

PS: @toniblyx have I missed anything?

**Comment by toniblyx** [comment]
Thanks for the insights here @w0rmr1d3r, I agree with you, I don't quite understand this issue. This is probably related with the way that is deploying/running Prowler.

@kingferiol Please provide more information about the issue and reopen it. Otherwise I'll close it.
