### ISSUE TITLE
Error running Security Hub integration for multiple regions

### ISSUE THREAD

**Issue by andyshinn** [toniblyx/prowler#914]
I am not sure if this is possible. In the notes it says (emphasis mine):

> Note 2: Since Prowler perform checks to all regions by defaults you **may** need to filter by region when runing Security Hub integration, as shown in the example above.

Is there a scenario where you do *not* need to run it per region?

The error is:

```
ERROR! Failed to send check output to AWS Security Hub
```

The policy attached to the instance profile running Prowler is:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "ProwlerImportSecurityHub",
            "Effect": "Allow",
            "Action": [
                "securityhub:GetFindings",
                "securityhub:DescribeHub",
                "securityhub:BatchImportFindings"
            ],
            "Resource": "*"
        }
    ]
}
```

Which I expect should allow importing to any region. But it seems to only work for the region it runs in.

I am looking to run Prowler for 20+ accounts in all regions. Does this mean I would need to run prowler 20 * region_count?

**Comment by toniblyx** [comment]
Thanks @andyshinn, this part of the documentation may need an update.

Well, as you say, the most common use case is to run Security Hub per region since it is a region based service so you are right. In order to run Prowler for 20+ accounts in all regions you need first to enable Security Hub on each account and each region using the commands (or any other automation way):
```
aws securityhub enable-security-hub --region <region>
aws securityhub enable-import-findings-for-product --region <region> --product-arn arn:aws:securityhub:<region>::product/prowler/prowler 
```
Once that is sorted out, you can run Prowler in many ways to get it done, using the multiaccount sample code here https://github.com/toniblyx/prowler/tree/master/util/org-multi-account (you need to adapt it) or using CodeBuild sample here https://github.com/toniblyx/prowler#codebuild-deployment (also needs some customizaton for you). In my opinion, for your particular requirements I would run Prowler using Fargate, it might be cheaper as well.

**Comment by andyshinn** [comment]
OK great. Thanks for the clarification. It sounds like it is indeed still a per account and per region thing for Security Hub.

In this case I was going to run it under SSM using an Automation document (start instance, pull Docker image, run Prowler, report to Security Hub, delete instance) triggered by EventBridge rule. I'll look into automating each region with something like Terraform.

**Comment by andyshinn** [comment]
Also, your Docker image seems to not be on 2.5.0, yet. Would be cool to get this repo hooked up to Docker Hub automated building on image tag ;)

**Comment by toniblyx** [comment]
Thanks @andyshinn I'm working on having all the automation back to Docker Hub and also an official ECR repo, I hope to have that sorted out soon.

**Comment by andyshinn** [comment]
Thanks for the real quick responses. Didn't know if GitHub was the best place for discussions like this. If there is a bette r place do let me know. Cheers. 👍

**Comment by toniblyx** [comment]
Feel free to reach out using github issues or my contact form at https://blyx.com/contact or Twitter my DMs are open or even the new Prowler Discord server https://discord.gg/UjSMCVnxSB
