### ISSUE TITLE
whitelist does not match exact S3-bucket

### ISSUE THREAD

**Issue by gregorschulz** [toniblyx/prowler#961]
If I want to whitelist **exactly** "mybucket.com"

`extra73:^mybucket\.com$
`
to match exactly "mybucket.com" and not "www.mybucket.com" the check gets a "FAIL" instead of "WARNING".

I see that "resource_value" gets expanded to `.*^mybucket\.com$.*` which works fine on the bash commandline:
```
check="mybucket.com"
resource_value=".*^mybucket\.com$.*"
if [[ $check =~ ${resource_value} ]] ; then echo "-> match"; fi
-> match
```
But not in a Prowler run.
Any ideas?
thx.

**Comment by toniblyx** [comment]
Thanks for the heads up @gregorschulz, I'd like to have @urjitbhatia input here since he wrote that feature and knows it better than me. 

Btw, I tried your command line in mac and fails due to the `echo "-> match!"` part. But in any case, it goes the way you say.

**Comment by gregorschulz** [comment]
> Thanks for the heads up @gregorschulz, I'd like to have @urjitbhatia input here since he wrote that feature and knows it better than me.

Thanks for that.

> Btw, I tried your command line in mac and fails due to the `echo "-> match!"` part. But in any case, it goes the way you say.

Yes, I've removed the "!" for a working output.

**Comment by n4ch04** [comment]
Hi @gregorschulz logic of whitelisting has been reformulated, now an exact match is needed to whitelist the element, please check it again

**Comment by n4ch04** [comment]
Closing this one

**Comment by derKrischan** [comment]
This should be marked as a breaking change IMO because it makes many current whitelists unusuable. They have to be refined for the exact match and the documentation needs an update.

In my case I have no idea what is the "exact" match for the the failure:

FAIL! eu-west-1: CloudFront distribution ABCDEFGH12345  has not Geo restrictions

where I used to accept it via whitelist with

extra732:ABCDEFGH12345

Now it is a failure and I'm going to pin my checks to version 2.7.0 as quick fix.

**Comment by toniblyx** [comment]
Thanks for the feedback @derKrischan, we are reopening it to see it in more detail. Can you share other use cases? We did our tests but need to increase the scope probably.

**Comment by n4ch04** [comment]
Hi , we will review it, right now it is picking up the nth argument from the log message to be compared with the whitelisted name, it seems that we need to extend the scope of the tests

**Comment by jansepke** [comment]
the change broke 90% of our whitelist, all of these whitelist entries are currently not working:

```
check29:VPCID
check122:IAMROLENAME
extra718:S3BUCKETNAME
extra728:SQSQUEUENAME
extra732:CLOUDFRONTID
extra734:S3BUCKETNAME
extra767:CLOUDFRONTID
extra773:CLOUDFRONTID
extra7156:APIGATEWAYID
```

**Comment by derKrischan** [comment]
We have the same experience like @jansepke. About 90% of our whitelist is broken and we use almost the same checks. The change is breaking because it is more strict than before.
As a first workaround we replaced the step
`git clone https://github.com/prowler-cloud/prowler`
from the installation instructions with
`git clone -b 2.7.0 https://github.com/prowler-cloud/prowler`
to be sure to use the latest release version.

**Comment by n4ch04** [comment]
@derKrischan @jansepke the change was intended to solve initial issue detected when you have various items with similar names (bucketname and 1bucketname, for example) and you only want to whitelist the most simple one. Since right now comparison only looks for the content of the whitelisted into the log name, it was going to generate false positives.
Exact matching implemented only worked in certain cases, so we are rolling it back to its previous version.
We have already created the PR to solve it :[PRWLR-151-fix-whitelist-checking](https://github.com/prowler-cloud/prowler/pull/1037)

Please check it, test your envs again and let us know if everything is ok

**Comment by n4ch04** [comment]
We are going to close the issue and merge the branch, a new reformulated logic for whitelisting process to include false positives is scheduled and will be included as new feature coming soon.

Please, let us know if any issues arise
